---

- name: "Ansible task"
  hosts: localhost
  connection: local 
  become: yes
  become_method: sudo

  tasks:

  - name: install epel-release
    yum:
      name: epel-release
      state: present   

  - name: Add Docker CE repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: 0644

  - name: Update all packages
    yum:
      name: '*'
      state: latest
      update_cache: yes

  - name: remove nginx
    yum:
      name: nginx
      state: absent

  - name: Install pre-requisite packages
    yum:
     name: "{{item}}"
     state: present
    loop:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

  - name: install the docker
    yum:
      name: 
        - docker
      state: present
     
  - name: Start and enable the Docker daemon
    ansible.builtin.service:
      name: docker
      state: started
      enabled: yes

  - name: Allow connections port 80
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: '80'
      ctstate: NEW
      jump: ACCEPT
      comment: Accept connections.

  - name: Put SELinux in permissive mode.
    selinux:
      state: disabled

  - name: Download and install Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755

  - name: Create a symbolic link
    ansible.builtin.file:
      src: /usr/local/bin/docker-compose
      dest: /usr/bin/docker-compose
      state: link    
